import { API_BASE_URL } from './config.js?v=1960-d21-cierre-etapa6-010926';
import { iniciarScanner, detenerScanner } from './scanner.js?v=1960-d21-cierre-etapa6-010926';
const $=id=>document.getElementById(id); const api=p=>`${String(API_BASE_URL||'').replace(/\/$/,'')}${p}`;
let lotes=[], producto=null, lotesProducto=[], accion='nuevo', loteReemplazo='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function json(path,opt={}){const r=await fetch(api(path),{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.mensaje||'No se pudo completar la operación');return d;}
function diasHasta(f){if(!f)return 99999;const hoy=new Date();hoy.setHours(0,0,0,0);return Math.ceil((new Date(`${f}T00:00:00`)-hoy)/86400000);}
function fmt(f){if(!f)return '—';const [y,m,d]=f.split('-');return `${d}/${m}/${y}`;}
function render(){
 const q=($('lotesBuscar')?.value||'').toLowerCase().trim(), rubro=document.querySelector('[data-lotes-rubro].activo')?.dataset.lotesRubro||'todos';
 const filtrados=lotes.filter(x=>(rubro==='todos'||x.rubro===rubro)&&(!q||`${x.articulo} ${x.codigo}`.toLowerCase().includes(q)));
 const codigos=new Set(lotes.map(x=>x.codigo)); const unidades=lotes.reduce((s,x)=>s+x.cantidad,0); const cortos=lotes.filter(x=>x.cortaFecha).length;
 $('lotesMetricaActivos').textContent=lotes.length; $('lotesMetricaUnidades').textContent=unidades.toLocaleString('es-AR'); $('lotesMetricaProductos').textContent=codigos.size; $('lotesMetricaCorta').textContent=cortos;
 $('lotesLista').innerHTML=filtrados.length?filtrados.map(x=>`<article class="lote-card ${x.cortaFecha?'is-short':''}"><div class="lote-card-top"><span class="lote-rubro">${esc(x.rubro)}</span>${x.cortaFecha?'<span class="lote-short">Corta fecha</span>':''}</div><h3>${esc(x.articulo)}</h3><small>EAN ${esc(x.codigo)}</small><div class="lote-card-data"><div><span>Vencimiento</span><b>${fmt(x.vencimiento)}</b></div><div><span>Cantidad</span><b>${x.cantidad} un.</b></div></div></article>`).join(''):'<div class="lotes-empty">Todavía no hay productos cargados.</div>';
}
async function cargar(){try{const d=await json('/lotes');lotes=d.lotes||[];render();}catch(e){$('lotesLista').innerHTML=`<div class="lotes-empty">${esc(e.message)}</div>`;}}
function modo(m){
 const inicio=$('lotesInicio'), camara=$('lotesCamara'), manual=$('lotesManual'), productoCard=$('lotesProducto');
 const hero=$('lotesHero'), divider=$('lotesDivider'), manualToggle=$('btnLotesManual'), manualCamara=$('btnLotesManualCamara');
 inicio.classList.toggle('oculto',m==='camara'||m==='producto');
 camara.classList.toggle('oculto',m!=='camara');
 manual.classList.toggle('oculto',m!=='manual');
 productoCard.classList.toggle('oculto',m!=='producto');
 hero?.classList.toggle('oculto',m==='manual');
 divider?.classList.toggle('oculto',m==='manual');
 manualToggle?.classList.toggle('oculto',m==='manual');
 manualCamara?.classList.toggle('oculto',m!=='camara');
 if(m==='manual') requestAnimationFrame(()=>$('lotesManualInput')?.focus());
}
async function abrir(){producto=null;lotesProducto=[];accion='nuevo';loteReemplazo='';$('lotesModal').classList.remove('oculto');$('lotesModal').setAttribute('aria-hidden','false');document.body.classList.add('lotes-modal-open');modo('inicio');requestAnimationFrame(()=>requestAnimationFrame(()=>escanear()));}
function cerrar(){detenerScanner();$('lotesModal').classList.add('oculto');$('lotesModal').setAttribute('aria-hidden','true');document.body.classList.remove('lotes-modal-open');}
async function escanear(){modo('camara');try{await iniciarScanner('videoLotes',seleccionarCodigo);}catch(e){modo('inicio');$('lotesCameraError').textContent='No se pudo iniciar la cámara. Revisá los permisos del navegador o usá el ingreso manual.';$('lotesCameraError').classList.remove('oculto');}}
async function seleccionarCodigo(codigo){detenerScanner();try{const d=await json(`/producto-maestro/${encodeURIComponent(codigo)}`);await preparar(d.producto);}catch(e){alert(e.message);modo('inicio');}}
async function preparar(p){producto=p;const d=await json(`/lotes/producto/${encodeURIComponent(p.codigo)}`);lotesProducto=d.lotes||[];$('lotesProductoNombre').textContent=p.articulo;$('lotesProductoCodigo').textContent=`Código: ${p.codigo}`;const rubroExistente=lotesProducto[0]?.rubro||'';$('lotesRubroCampo').classList.toggle('oculto',Boolean(rubroExistente));$('lotesRubro').value=rubroExistente||'';$('lotesFecha').value='';$('lotesCantidad').value='1';$('lotesCorta').checked=false;
 if(lotesProducto.length){accion='agregar';$('lotesExistentes').classList.remove('oculto');$('lotesExistentes').innerHTML=`<strong>Lotes cargados</strong>${lotesProducto.map(x=>`<div class="lote-existing"><span><b>${fmt(x.vencimiento)}</b><small>${x.cantidad} un.</small></span><button type="button" data-reemplazar-lote="${esc(x.id)}">Reemplazar</button></div>`).join('')}<button class="lote-add-new" type="button" id="lotesAgregarNuevo">+ Agregar lote nuevo</button>`;$('lotesForm').classList.add('oculto');document.querySelectorAll('[data-reemplazar-lote]').forEach(b=>b.onclick=()=>{accion='reemplazar';loteReemplazo=b.dataset.reemplazarLote;$('lotesForm').classList.remove('oculto');});$('lotesAgregarNuevo').onclick=()=>{accion='agregar';loteReemplazo='';$('lotesForm').classList.remove('oculto');};}else{$('lotesExistentes').classList.add('oculto');$('lotesForm').classList.remove('oculto');accion='nuevo';}
 modo('producto');}
async function buscarManual(){const q=$('lotesManualInput').value.trim();if(!q)return;try{const d=await json('/productos-maestro');const items=(d.productos||[]).filter(p=>`${p.articulo} ${p.codigo}`.toLowerCase().includes(q.toLowerCase())).slice(0,12);$('lotesSugerencias').innerHTML=items.map(p=>`<button class="manual-suggestion-item" type="button" data-codigo="${esc(p.codigo)}"><strong>${esc(p.articulo)}</strong><span>${esc(p.codigo)}</span></button>`).join('')||'<div class="manual-no-results">No se encontraron productos.</div>';$('lotesSugerencias').classList.remove('oculto');$('lotesSugerencias').querySelectorAll('[data-codigo]').forEach(b=>b.onclick=()=>seleccionarCodigo(b.dataset.codigo));}catch(e){alert(e.message);}}
async function guardar(){if(!producto)return;const vencimiento=$('lotesFecha').value,cantidad=Number($('lotesCantidad').value),rubro=$('lotesRubro').value,cortaFecha=$('lotesCorta').checked;if(!vencimiento||!Number.isInteger(cantidad)||cantidad<=0)return alert('Completá fecha de vencimiento y una cantidad válida.');if(!lotesProducto.length&&!rubro)return alert('Seleccioná Fiambrería o Lácteos.');const body={codigo:producto.codigo,articulo:producto.articulo,rubro:rubro||lotesProducto[0]?.rubro,vencimiento,cantidad,cortaFecha};try{if(accion==='reemplazar')await json(`/lotes/${encodeURIComponent(loteReemplazo)}`,{method:'PUT',body:JSON.stringify(body)});else await json('/lotes',{method:'POST',body:JSON.stringify(body)});await cargar();producto=null;modo('camara');await escanear();}catch(e){alert(e.message);}}
function activar(){cargar();}
$('lotesFab')?.addEventListener('click',abrir);$('btnLotesCargaHeader')?.addEventListener('click',abrir);$('btnLotesCerrar')?.addEventListener('click',cerrar);$('lotesBackdrop')?.addEventListener('click',cerrar);$('btnLotesCamara')?.addEventListener('click',escanear);$('btnLotesManual')?.addEventListener('click',()=>modo('manual'));$('btnLotesManualCamara')?.addEventListener('click',()=>{detenerScanner();modo('manual')});$('btnLotesVolverScanner')?.addEventListener('click',escanear);$('btnLotesBuscarManual')?.addEventListener('click',buscarManual);$('lotesManualInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')buscarManual()});$('btnLotesGuardar')?.addEventListener('click',guardar);$('lotesBuscar')?.addEventListener('input',render);document.querySelectorAll('[data-lotes-rubro]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-lotes-rubro]').forEach(x=>x.classList.remove('activo'));b.classList.add('activo');render();});window.LotesModule={activar,cerrar,reiniciar:cerrar};
