const empleados = ["Mica", "Agustín", "Maxi", "Ariana", "Joaquín", "Bruno"];
const TURNOS = [
  { id: "8-16", label: "8-16", clase: "turno-naranja" }, { id: "8-13", label: "8-13", clase: "turno-amarillo" },
  { id: "9-14", label: "9-14", clase: "turno-azul" }, { id: "10-16", label: "10-16", clase: "turno-celeste" },
  { id: "14-22", label: "14-22", clase: "turno-rojo" }, { id: "16-22", label: "16-22", clase: "turno-violeta" },
  { id: "franco", label: "Franco", clase: "turno-franco" }, { id: "vacaciones", label: "Vacaciones", clase: "turno-verde" },
  { id: "personalizado", label: "Personalizado", clase: "turno-personalizado" }
];
let fechaVista = new Date(new Date().getFullYear(), new Date().getMonth(), 1), vistaActual = "equipo", diaSeleccionado = new Date().getDate();
let edicionActual = null, restaurarBottomNav = [], modoPincel = false, turnoPincel = "8-16", arrastrando = false, seleccionInicio = null;
let historial = [], rehacer = [], portapapeles = [], seleccion = new Set();
const datos = new Map(), $ = id => document.getElementById(id);
const keyCelda = (empleado,dia)=>`${empleado}::${dia}`;
function clave(empleado,dia){return `${fechaVista.getFullYear()}-${fechaVista.getMonth()}-${dia}-${empleado}`;}
function turnoEjemplo(i,d){const s=[["8-16","8-16","franco","16-22","16-22","8-13","franco"],["8-13","8-13","8-16","franco","16-22","16-22","franco"],["16-22","16-22","franco","8-16","8-16","14-22","franco"],["14-22","14-22","8-16","8-16","franco","16-22","franco"],["9-14","9-14","vacaciones","vacaciones","vacaciones","franco","franco"],["10-16","10-16","franco","14-22","14-22","8-16","franco"]];return s[i][(d-1)%7];}
function obtenerTurno(e,d){return datos.get(clave(e,d))||turnoEjemplo(empleados.indexOf(e),d);}
function obtenerDefinicion(id){return TURNOS.find(t=>t.id===id)||{id,label:id||"—",clase:"turno-personalizado"};}
function diasDelMes(){return new Date(fechaVista.getFullYear(),fechaVista.getMonth()+1,0).getDate();}
function nombreMes(){return fechaVista.toLocaleDateString("es-AR",{month:"long",year:"numeric"});}
function nombreDia(d){return new Date(fechaVista.getFullYear(),fechaVista.getMonth(),d).toLocaleDateString("es-AR",{weekday:"short"}).replace(".","").toUpperCase();}
function esMesActual(){const h=new Date();return fechaVista.getFullYear()===h.getFullYear()&&fechaVista.getMonth()===h.getMonth();}
function esHoy(d){return esMesActual()&&d===new Date().getDate();}
function coberturaDia(d){let manana=0,tarde=0;empleados.forEach(e=>{const id=obtenerTurno(e,d);if(["8-16","8-13","9-14","10-16"].includes(id))manana++;if(["14-22","16-22","8-16"].includes(id))tarde++;});return{manana,tarde};}
function guardarEstado(){historial.push(new Map(datos));if(historial.length>40)historial.shift();rehacer=[];actualizarAcciones();}
function deshacer(){if(!historial.length)return;rehacer.push(new Map(datos));const prev=historial.pop();datos.clear();prev.forEach((v,k)=>datos.set(k,v));renderTodo();actualizarAcciones();}
function rehacerCambio(){if(!rehacer.length)return;historial.push(new Map(datos));const next=rehacer.pop();datos.clear();next.forEach((v,k)=>datos.set(k,v));renderTodo();actualizarAcciones();}
function actualizarAcciones(){$("horariosUndo")&&( $("horariosUndo").disabled=!historial.length);$("horariosRedo")&&( $("horariosRedo").disabled=!rehacer.length);$("horariosPaste")&&( $("horariosPaste").disabled=!portapapeles.length||!seleccion.size);const c=$("horariosSeleccionCount");if(c)c.textContent=seleccion.size?`${seleccion.size} seleccionada${seleccion.size>1?"s":""}`:"";}
function aplicarTurnoASeleccion(turno){if(!seleccion.size)return;guardarEstado();seleccion.forEach(k=>{const [e,d]=k.split("::");datos.set(clave(e,Number(d)),turno);});renderTodo();}
function crearBarraProductividad(){if($("horariosProductividad"))return;const div=document.createElement("div");div.id="horariosProductividad";div.className="horarios-productividad";div.innerHTML=`<button id="horariosUndo" title="Deshacer">↶</button><button id="horariosRedo" title="Rehacer">↷</button><button id="horariosPaint" title="Pincel">🖌 <span>Pintar</span></button><select id="horariosPaintTurno">${TURNOS.filter(t=>t.id!=="personalizado").map(t=>`<option value="${t.id}">${t.label}</option>`).join("")}</select><button id="horariosCopy">Copiar</button><button id="horariosPaste">Pegar</button><button id="horariosClearSel">Limpiar</button><small id="horariosSeleccionCount"></small>`;document.querySelector(".horarios-status-row")?.after(div);
  $("horariosUndo").onclick=deshacer;$("horariosRedo").onclick=rehacerCambio;$("horariosPaint").onclick=()=>{modoPincel=!modoPincel;$("horariosPaint").classList.toggle("activo",modoPincel);};$("horariosPaintTurno").onchange=e=>turnoPincel=e.target.value;
  $("horariosCopy").onclick=()=>{portapapeles=[...seleccion].map(k=>{const[e,d]=k.split("::");return{empleado:e,dia:Number(d),turno:obtenerTurno(e,Number(d))};});actualizarAcciones();};
  $("horariosPaste").onclick=()=>{if(!portapapeles.length||!seleccion.size)return;guardarEstado();const targets=[...seleccion];targets.forEach((k,i)=>{const[e,d]=k.split("::"),src=portapapeles[i%portapapeles.length];datos.set(clave(e,Number(d)),src.turno);});renderTodo();};
  $("horariosClearSel").onclick=()=>{seleccion.clear();renderTabla();actualizarAcciones();};actualizarAcciones();
}
function desplazarAlDia(d,b="smooth"){requestAnimationFrame(()=>{const w=document.querySelector("#horariosEquipoView .horarios-table-wrap"),c=document.querySelector(`#horariosTablaHead [data-horarios-dia="${d}"]`),e=document.querySelector("#horariosTablaHead .empleado-col");if(w&&c)w.scrollTo({left:Math.max(0,c.offsetLeft-(e?.offsetWidth||0)-12),behavior:b});});}
function actualizarColumnaEmpleados(){const w=document.querySelector("#horariosEquipoView .horarios-table-wrap"),t=document.querySelector("#horariosEquipoView .horarios-table");if(!w||!t)return;t.classList.toggle("empleados-compactos",w.scrollLeft>32);t.classList.toggle("empleados-minimos",w.scrollLeft>240);}
function seleccionarCelda(e,d,agregar=false){if(!agregar)seleccion.clear();seleccion.add(keyCelda(e,d));diaSeleccionado=d;renderTabla();renderResumen();actualizarAcciones();}
function seleccionarRango(e2,d2){if(!seleccionInicio)return;const i1=empleados.indexOf(seleccionInicio.empleado),i2=empleados.indexOf(e2),d1=seleccionInicio.dia;seleccion.clear();for(let i=Math.min(i1,i2);i<=Math.max(i1,i2);i++)for(let d=Math.min(d1,d2);d<=Math.max(d1,d2);d++)seleccion.add(keyCelda(empleados[i],d));renderTabla();actualizarAcciones();}
function renderTabla(){const head=$("horariosTablaHead"),body=$("horariosTablaBody");if(!head||!body)return;head.innerHTML=`<tr><th class="empleado-col"><span class="empleado-titulo-completo">Empleado</span><span class="empleado-titulo-corto">Emp.</span></th>${Array.from({length:diasDelMes()},(_,i)=>{const d=i+1,f=new Date(fechaVista.getFullYear(),fechaVista.getMonth(),d),finde=[0,6].includes(f.getDay()),h=esHoy(d),c=coberturaDia(d);return `<th class="${finde?"fin-semana":""} ${h?"dia-hoy":""} ${d===diaSeleccionado?"dia-seleccionado":""}" data-horarios-dia="${d}"><span>${nombreDia(d)}</span><strong>${d}</strong><small class="cobertura-mini"><b>☀${c.manana}</b><b>☾${c.tarde}</b></small></th>`;}).join("")}</tr>`;
body.innerHTML=empleados.map(e=>`<tr><th class="empleado-col"><span class="empleado-avatar">${e[0]}</span><strong>${e}</strong></th>${Array.from({length:diasDelMes()},(_,i)=>{const d=i+1,t=obtenerDefinicion(obtenerTurno(e,d)),sel=seleccion.has(keyCelda(e,d));return `<td class="${esHoy(d)?"dia-hoy":""} ${d===diaSeleccionado?"dia-seleccionado":""} ${sel?"celda-seleccionada":""}" data-empleado="${e}" data-dia="${d}"><button type="button" class="horario-cell ${t.clase}">${t.label}</button></td>`;}).join("")}</tr>`).join("");
head.querySelectorAll("[data-horarios-dia]").forEach(x=>x.onclick=()=>{diaSeleccionado=Number(x.dataset.horariosDia);renderTabla();renderResumen();});
body.querySelectorAll("td[data-empleado]").forEach(td=>{td.onpointerdown=e=>{e.preventDefault();const emp=td.dataset.empleado,d=Number(td.dataset.dia);if(modoPincel){seleccion=new Set([keyCelda(emp,d)]);aplicarTurnoASeleccion(turnoPincel);return;}arrastrando=true;seleccionInicio={empleado:emp,dia:d};seleccionarCelda(emp,d,e.ctrlKey||e.metaKey);};td.onpointerenter=()=>{if(arrastrando)seleccionarRango(td.dataset.empleado,Number(td.dataset.dia));};td.ondblclick=()=>abrirEditor(td.dataset.empleado,Number(td.dataset.dia));});
const w=document.querySelector("#horariosEquipoView .horarios-table-wrap");if(w&&!w.dataset.cfg){w.dataset.cfg="1";w.addEventListener("scroll",actualizarColumnaEmpleados,{passive:true});}actualizarColumnaEmpleados();}
document.addEventListener("pointerup",()=>arrastrando=false);
function renderResumen(){const t=$("horariosDiaSeleccionado"),c=$("horariosResumenDia");if(!t||!c)return;const f=new Date(fechaVista.getFullYear(),fechaVista.getMonth(),diaSeleccionado);t.textContent=f.toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"});const m=new Map();empleados.forEach(e=>{const id=obtenerTurno(e,diaSeleccionado);m.set(id,(m.get(id)||0)+1);});c.innerHTML=[...m].map(([id,n])=>{const x=obtenerDefinicion(id);return `<div><span><i class="${x.clase}"></i>${x.label}</span><strong>${n} ${n===1?"persona":"personas"}</strong></div>`;}).join("");const cv=coberturaDia(diaSeleccionado),b=$("horariosCoberturaEstado");if(b){b.textContent=`Mañana ${cv.manana} · Tarde ${cv.tarde}`;b.classList.toggle("alerta",cv.manana<2||cv.tarde<2);}}
function abrirEditor(e,d){edicionActual={empleado:e,dia:d,turno:obtenerTurno(e,d)};$("horariosEditorEmpleado").textContent=seleccion.size>1?`${seleccion.size} turnos`:e;$("horariosEditorFecha").textContent=seleccion.size>1?"Aplicar a la selección":new Date(fechaVista.getFullYear(),fechaVista.getMonth(),d).toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"});const o=$("horariosTurnosOpciones");o.innerHTML=TURNOS.map(t=>`<button type="button" class="horarios-turno-option ${t.clase} ${t.id===edicionActual.turno?"seleccionado":""}" data-turno="${t.id}"><span></span><strong>${t.label}</strong><em>✓</em></button>`).join("");o.querySelectorAll("[data-turno]").forEach(btn=>btn.onclick=()=>{edicionActual.turno=btn.dataset.turno;o.querySelectorAll("[data-turno]").forEach(b=>b.classList.toggle("seleccionado",b===btn));$("horariosCustomWrap").classList.toggle("oculto",btn.dataset.turno!=="personalizado");});$("horariosCustomWrap").classList.toggle("oculto",TURNOS.some(t=>t.id===edicionActual.turno));$("horariosTurnoPersonalizado").value=TURNOS.some(t=>t.id===edicionActual.turno)?"":edicionActual.turno;$("horariosEditor").classList.remove("oculto");$("horariosEditor").setAttribute("aria-hidden","false");}
function cerrarEditor(){$("horariosEditor")?.classList.add("oculto");$("horariosEditor")?.setAttribute("aria-hidden","true");edicionActual=null;}
function guardarEdicion(){if(!edicionActual)return;let turno=edicionActual.turno;if(turno==="personalizado"){turno=$("horariosTurnoPersonalizado").value.trim();if(!turno)return $("horariosTurnoPersonalizado").focus();}if(seleccion.size>1)aplicarTurnoASeleccion(turno);else{guardarEstado();datos.set(clave(edicionActual.empleado,edicionActual.dia),turno);renderTodo();}cerrarEditor();}
function renderMiHorario(){const e="Agustín",lista=$("miHorarioLista");if(!lista)return;const h=new Date(),ini=esMesActual()?h.getDate():1,dias=Array.from({length:Math.min(10,diasDelMes()-ini+1)},(_,i)=>ini+i);let horas=0,francos=0,vac=0;for(let d=1;d<=diasDelMes();d++){const id=obtenerTurno(e,d);if(id==="franco")francos++;else if(id==="vacaciones")vac++;else{const p=id.match(/(\d+)-(\d+)/);if(p)horas+=Number(p[2])-Number(p[1]);}}let stats=$("miHorarioStats");if(!stats){stats=document.createElement("section");stats.id="miHorarioStats";stats.className="mi-horario-stats";$("miHorarioLista").before(stats);}stats.innerHTML=`<article><strong>${horas}</strong><span>Horas del mes</span></article><article><strong>${francos}</strong><span>Francos</span></article><article><strong>${vac}</strong><span>Vacaciones</span></article>`;lista.innerHTML=dias.map(d=>{const tr=obtenerDefinicion(obtenerTurno(e,d)),f=new Date(fechaVista.getFullYear(),fechaVista.getMonth(),d);return `<article><div><span>${f.toLocaleDateString("es-AR",{weekday:"long"})}</span><strong>${d} de ${f.toLocaleDateString("es-AR",{month:"long"})}</strong></div><span class="mi-turno-pill ${tr.clase}">${tr.label}</span></article>`;}).join("");const p=dias.find(d=>!["franco","vacaciones"].includes(obtenerTurno(e,d)))||dias[0],tr=obtenerDefinicion(obtenerTurno(e,p));$("miHorarioProximo").textContent=tr.label;$("miHorarioProximoFecha").textContent=new Date(fechaVista.getFullYear(),fechaVista.getMonth(),p).toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long"});}
function cambiarVista(v){vistaActual=v;const eq=v==="equipo";$("horariosEquipoView")?.classList.toggle("oculto",!eq);$("horariosMioView")?.classList.toggle("oculto",eq);$("horariosTituloVista").textContent=eq?"Horario del equipo":"Mi horario";$("horariosSubtituloVista").textContent=eq?"Vista mensual de todos los empleados":"Tus próximos turnos y francos";document.querySelectorAll("[data-horarios-vista]").forEach(b=>b.classList.toggle("activo",b.dataset.horariosVista===v));if(!eq)renderMiHorario();}
function cambiarMes(n){fechaVista=new Date(fechaVista.getFullYear(),fechaVista.getMonth()+n,1);diaSeleccionado=esMesActual()?new Date().getDate():1;seleccion.clear();renderTodo();}
function irAHoy(){const h=new Date();fechaVista=new Date(h.getFullYear(),h.getMonth(),1);diaSeleccionado=h.getDate();cambiarVista("equipo");renderTodo();desplazarAlDia(diaSeleccionado);}
function renderTodo(){if($("horariosMesTexto"))$("horariosMesTexto").textContent=nombreMes();renderTabla();renderResumen();renderMiHorario();actualizarAcciones();}
function configurarEventos(){crearBarraProductividad();$("btnHorariosMesAnterior")?.addEventListener("click",()=>cambiarMes(-1));$("btnHorariosMesSiguiente")?.addEventListener("click",()=>cambiarMes(1));$("btnHorariosHoy")?.addEventListener("click",irAHoy);$("btnHorariosHoyToolbar")?.addEventListener("click",irAHoy);$("btnCerrarHorariosEditor")?.addEventListener("click",cerrarEditor);$("btnCancelarHorario")?.addEventListener("click",cerrarEditor);$("btnGuardarHorario")?.addEventListener("click",guardarEdicion);document.querySelectorAll("[data-horarios-vista]").forEach(b=>b.addEventListener("click",()=>cambiarVista(b.dataset.horariosVista)));document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?rehacerCambio():deshacer();}if(e.key==="Escape"){modoPincel=false;$("horariosPaint")?.classList.remove("activo");cerrarEditor();}});}
function activar(){restaurarBottomNav=[];document.querySelectorAll(".app-bottom-nav").forEach(n=>{restaurarBottomNav.push([n,n.style.display]);n.style.display="none";});renderTodo();cambiarVista(vistaActual);if(esMesActual())desplazarAlDia(new Date().getDate(),"auto");}
function desactivar(){cerrarEditor();restaurarBottomNav.forEach(([n,d])=>n.style.display=d);restaurarBottomNav=[];}
configurarEventos();window.HorariosModule={activar,desactivar};
